server:
  port: 8000
  compression:
    enabled: true
  http2:
    enabled: true

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/sample
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform:
  flyway:
    enabled: true
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
      additional-paths:
        - src/main/java/
        - src/main/resources

application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days